:: Generated by: https://github.com/swagger-api/swagger-codegen.git
::

@echo off

dotnet restore src\WsWawiOrderList
dotnet build src\WsWawiOrderList
echo Now, run the following to start the project: dotnet run -p src\WsWawiOrderList\WsWawiOrderList.csproj --launch-profile web.
echo.
